name: Daily Website Screenshot

on:
  schedule:
    # Runs daily at 12:05 AM IST (18:35 UTC previous day)
    - cron: '35 18 * * *'
  workflow_dispatch: # allows manual trigger

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm init -y
          npm i -D playwright
          npx playwright install --with-deps

      - name: Take Screenshot
        run: |
          mkdir -p screenshots
          TIMESTAMP=$(date +"%Y-%m-%d")
          npx playwright screenshot "https://leetcode-grinder.netlify.app/" \
            -o screenshots/${TIMESTAMP}.png --full-page

      - name: Commit and push screenshot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          TIMESTAMP=$(date +"%Y-%m-%d")
          git add screenshots/${TIMESTAMP}.png
          git commit -m "Add screenshot for ${TIMESTAMP}" || echo "No new screenshot"
          git push

      - name: Send Screenshot Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily SS LC Digger - ${{ github.run_number }}"
          to: "rithvik.matta@gmail.com,rishi.sheth19@gmail.com,raghav4engg@gmail.com,rithishbarath6@gmail.com,sanjit2devmaheswaran@gmail.com,rishil.aj99@gmail.com"
          from: "Daily Bot <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            Hello 👋,
            
            Here’s the daily screenshot of your website (https://leetcode-grinder.netlify.app/) taken at 12:05 AM IST.
            
            Hope you finished yesterday's LeetCode question — else you owe everyone else chocolates 🍫😈  
            Muhahahahahahahahahahaha

            Best,  
            GitHub Actions Bot 🤖 → Made by rtk
          attachments: screenshots/${{ github.run_number }}.png

      - name: Cleanup old screenshots
        run: |
          find screenshots -type f -mtime +30 -delete
